// Code generated by protoc-gen-go. DO NOT EDIT.
// source: host_agent.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

const _ = proto.ProtoPackageIsVersion3

// HostMessage message
type HostMessage struct {
	HostId               string    `protobuf:"bytes,10,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp            int64     `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Heartbeat            *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof" json:"heartbeat,omitempty"`
	ResourceReport       *ResourceReport `protobuf:"bytes,2,opt,name=resource_report,json=resourceReport,proto3,oneof" json:"resource_report,omitempty"`
}

func (m *HostMessage) Reset()         { *m = HostMessage{} }
func (m *HostMessage) String() string { return proto.CompactTextString(m) }
func (*HostMessage) ProtoMessage()    {}

// MasterMessage message
type MasterMessage struct {
	InstructionId        string    `protobuf:"bytes,10,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	Timestamp            int64     `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CreateDesktop        *CreateDesktopInstruction `protobuf:"bytes,1,opt,name=create_desktop,json=createDesktop,proto3,oneof" json:"create_desktop,omitempty"`
	TerminateDesktop     *TerminateDesktopInstruction `protobuf:"bytes,2,opt,name=terminate_desktop,json=terminateDesktop,proto3,oneof" json:"terminate_desktop,omitempty"`
}

func (m *MasterMessage) Reset()         { *m = MasterMessage{} }
func (m *MasterMessage) String() string { return proto.CompactTextString(m) }
func (*MasterMessage) ProtoMessage()    {}

// RegisterHostRequest message
type RegisterHostRequest struct {
	Hostname             string    `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress            string    `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	OsType               string    `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	CpuCores             int32     `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	TotalRamMb           int64     `protobuf:"varint,5,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	MaxSessions          int32     `protobuf:"varint,6,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	AgentVersion         string    `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Gpus                 []*GPUInfo `protobuf:"bytes,8,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Region               string    `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	Az                   string    `protobuf:"bytes,10,opt,name=az,proto3" json:"az,omitempty"`
}

func (m *RegisterHostRequest) Reset()         { *m = RegisterHostRequest{} }
func (m *RegisterHostRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterHostRequest) ProtoMessage()    {}

// RegisterHostResponse message
type RegisterHostResponse struct {
	HostId               string    `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentToken           string    `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	Success              bool      `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (m *RegisterHostResponse) Reset()         { *m = RegisterHostResponse{} }
func (m *RegisterHostResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterHostResponse) ProtoMessage()    {}

// GPUInfo message
type GPUInfo struct {
	Model                string    `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Count                int32     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MemoryMb             int64     `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
}

func (m *GPUInfo) Reset()         { *m = GPUInfo{} }
func (m *GPUInfo) String() string { return proto.CompactTextString(m) }
func (*GPUInfo) ProtoMessage()    {}

// Heartbeat message
type Heartbeat struct {
	Sequence             int64     `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}

// ResourceReport message
type ResourceReport struct {
	CpuUsagePercent      float32   `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	AvailableRamMb       int64     `protobuf:"varint,2,opt,name=available_ram_mb,json=availableRamMb,proto3" json:"available_ram_mb,omitempty"`
	ActiveSessions       int32     `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	GpuUsagePercent      float32   `protobuf:"fixed32,4,opt,name=gpu_usage_percent,json=gpuUsagePercent,proto3" json:"gpu_usage_percent,omitempty"`
	AvailableGpuMemoryMb int64     `protobuf:"varint,5,opt,name=available_gpu_memory_mb,json=availableGpuMemoryMb,proto3" json:"available_gpu_memory_mb,omitempty"`
	DiskUsagePercent     float32   `protobuf:"fixed32,6,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
}

func (m *ResourceReport) Reset()         { *m = ResourceReport{} }
func (m *ResourceReport) String() string { return proto.CompactTextString(m) }
func (*ResourceReport) ProtoMessage()    {}

// DesktopStatusUpdate message
type DesktopStatusUpdate struct {
	SessionId            string    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status               string    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (m *DesktopStatusUpdate) Reset()         { *m = DesktopStatusUpdate{} }
func (m *DesktopStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*DesktopStatusUpdate) ProtoMessage()    {}

// DesktopSessionInfo message
type DesktopSessionInfo struct {
	SessionId            string    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Protocol             string    `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostIp               string    `protobuf:"bytes,3,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Port                 int32     `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Password             string    `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	NativeUrl            string    `protobuf:"bytes,6,opt,name=native_url,json=nativeUrl,proto3" json:"native_url,omitempty"`
	CreatedAt            int64     `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *DesktopSessionInfo) Reset()         { *m = DesktopSessionInfo{} }
func (m *DesktopSessionInfo) String() string { return proto.CompactTextString(m) }
func (*DesktopSessionInfo) ProtoMessage()    {}

// CreateDesktopInstruction message
type CreateDesktopInstruction struct {
	SessionId            string    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Username             string    `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Protocol             string    `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Resolution           string    `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	ColorDepth           int32     `protobuf:"varint,5,opt,name=color_depth,json=colorDepth,proto3" json:"color_depth,omitempty"`
	TimeoutMinutes       int32     `protobuf:"varint,6,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	RequireGpu           bool      `protobuf:"varint,7,opt,name=require_gpu,json=requireGpu,proto3" json:"require_gpu,omitempty"`
	RequestedGpuCount    int32     `protobuf:"varint,8,opt,name=requested_gpu_count,json=requestedGpuCount,proto3" json:"requested_gpu_count,omitempty"`
}

func (m *CreateDesktopInstruction) Reset()         { *m = CreateDesktopInstruction{} }
func (m *CreateDesktopInstruction) String() string { return proto.CompactTextString(m) }
func (*CreateDesktopInstruction) ProtoMessage()    {}

// TerminateDesktopInstruction message
type TerminateDesktopInstruction struct {
	SessionId            string    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Force                bool      `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

func (m *TerminateDesktopInstruction) Reset()         { *m = TerminateDesktopInstruction{} }
func (m *TerminateDesktopInstruction) String() string { return proto.CompactTextString(m) }
func (*TerminateDesktopInstruction) ProtoMessage()    {}

// UpdateConfigInstruction message
type UpdateConfigInstruction struct {
	MaxSessions          int32     `protobuf:"varint,1,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	HeartbeatIntervalSeconds int64 `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
}

func (m *UpdateConfigInstruction) Reset()         { *m = UpdateConfigInstruction{} }
func (m *UpdateConfigInstruction) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigInstruction) ProtoMessage()    {}

func init() {
	proto.RegisterType((*HostMessage)(nil), "hostagent.HostMessage")
	proto.RegisterType((*MasterMessage)(nil), "hostagent.MasterMessage")
	proto.RegisterType((*RegisterHostRequest)(nil), "hostagent.RegisterHostRequest")
	proto.RegisterType((*RegisterHostResponse)(nil), "hostagent.RegisterHostResponse")
	proto.RegisterType((*GPUInfo)(nil), "hostagent.GPUInfo")
	proto.RegisterType((*Heartbeat)(nil), "hostagent.Heartbeat")
	proto.RegisterType((*ResourceReport)(nil), "hostagent.ResourceReport")
	proto.RegisterType((*DesktopStatusUpdate)(nil), "hostagent.DesktopStatusUpdate")
	proto.RegisterType((*DesktopSessionInfo)(nil), "hostagent.DesktopSessionInfo")
	proto.RegisterType((*CreateDesktopInstruction)(nil), "hostagent.CreateDesktopInstruction")
	proto.RegisterType((*TerminateDesktopInstruction)(nil), "hostagent.TerminateDesktopInstruction")
	proto.RegisterType((*UpdateConfigInstruction)(nil), "hostagent.UpdateConfigInstruction")
}
